version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 99
  labels:
  - Automatic
  ignore:
  - dependency-name: webpack
    versions:
    - 5.34.0
  - dependency-name: css-loader
    versions:
    - 5.2.3
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 99
  labels:
  - Automatic
