# ASF-ui is a node.js project
language: node_js

# We can save bandwidth by limiting git clone to only last 10 commits
git:
  depth: 10

# Use latest images for building: https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images
group: travis_latest

# We target latest stable version of node.js
node_js: node

script:
  - |
    set -eu

#    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
#        set +eu # This is needed to run below npm command on OSX
#    fi

    npm run-script build --no-progress

#    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
#        set -eu # We no longer need +eu on OSX
#    fi

    set +u # This is needed to continue Travis build
matrix:
  # We can use fast finish, as we don't need to wait for allow_failures builds to mark build as success
  fast_finish: true
  include:
    # We're building ASF-ui with node.js on latest versions of Linux and OS X
    # Sadly, travis is still missing support for selecting latest images: https://github.com/travis-ci/travis-ci/issues/8922
    - os: linux
      # Ref: https://docs.travis-ci.com/user/reference/trusty
      dist: trusty
      sudo: false
    - os: osx
      # Ref: https://docs.travis-ci.com/user/reference/osx
      osx_image: xcode10
