version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  linux:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install npm modules
          command: npm ci --no-progress
      - run:
          name: Build npm project
          command: npm run-script build:ci --no-progress
      - run:
          name: Create artifacts
          command: |
            set -eu

            mkdir -p /tmp/artifacts

            compressionArgs="-mx=1"

            if [ -n "${CIRCLE_TAG-}" ]; then
                compressionArgs="-mx=9 -mpass=15 -mfb=258"
            fi

            7z a -bd -tzip -mm=Deflate $compressionArgs "/tmp/artifacts/ASF-ui.zip" "${CIRCLE_WORKING_DIRECTORY}/dist/*"
      - store_artifacts:
          path: /tmp/artifacts

  osx:
    macos:
      xcode: "11.2.0"
    steps:
      - checkout
      - run:
          name: Install npm modules
          command: npm ci --no-progress
      - run:
          name: Build npm project
          command: npm run-script build:ci --no-progress

  windows:
    executor: windows/default
    steps:
      - checkout
      - run:
          name: Install npm modules
          command: npm ci --no-progress
      - run:
          name: Build npm project
          command: npm run-script build:ci --no-progress

workflows:
  version: 2
  ci:
    jobs:
      - linux
#      - osx
      - windows
