name: 'ASF-ui-lock-threads'

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - name: Lock inactive threads
        uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-inactive-days: 30
          pr-lock-inactive-days: 30
          issue-lock-comment: >
            This issue has been automatically locked since there
            has not been any recent activity after it was closed.
          pr-lock-comment: >
            This pull request has been automatically locked since there
            has not been any recent activity after it was closed.
